#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
CERT_DIR="$ROOT/certs"
SECRET_DIR="$ROOT/secrets"
BACKUP_DIR="$ROOT/backups"
CONFIG_DIR="$ROOT/config"
TITLE="OTLP Proxy AIO Installer"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-otlp-proxy-aio}"

have() { command -v "$1" >/dev/null 2>&1; }
run_root() {
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then "$@"; elif have sudo; then sudo "$@"; else return 127; fi
}

install_dialog() {
  have dialog && return 0
  echo "dialog is required; attempting to install it..."
  if have apt-get; then run_root apt-get update && run_root apt-get install -y dialog openssl
  elif have dnf; then run_root dnf install -y dialog openssl
  elif have yum; then run_root yum install -y dialog openssl
  elif have pacman; then run_root pacman -Sy --noconfirm dialog openssl
  elif have apk; then run_root apk add dialog openssl
  else
    echo "No supported package manager found. Install 'dialog' and 'openssl' first." >&2
    exit 1
  fi
}

install_docker_best_effort() {
  if have docker && docker compose version >/dev/null 2>&1; then return 0; fi
  msgbox "Docker Engine + Docker Compose plugin are required. The installer can try your distro packages. If your distro package is unavailable, install Docker manually and rerun this installer."
  if ! yesno "Attempt to install Docker from this distribution's package manager now?"; then return 1; fi
  if have apt-get; then
    run_root apt-get update
    run_root apt-get install -y docker.io docker-compose-v2 || run_root apt-get install -y docker.io docker-compose
  elif have dnf; then
    run_root dnf install -y docker docker-compose-plugin || run_root dnf install -y moby-engine docker-compose
  elif have yum; then
    run_root yum install -y docker docker-compose-plugin || run_root yum install -y docker docker-compose
  elif have pacman; then
    run_root pacman -Sy --noconfirm docker docker-compose
  elif have apk; then
    run_root apk add docker docker-cli-compose
  else
    return 1
  fi
  if have systemctl; then run_root systemctl enable --now docker || true; fi
  have docker && docker compose version >/dev/null 2>&1
}

install_dialog

ui() { dialog --clear --backtitle "$TITLE" "$@"; }
msgbox() { ui --title "$TITLE" --msgbox "$1" 12 72; }
yesno() { ui --title "$TITLE" --yesno "$1" 12 72; }
inputbox() { ui --stdout --title "$TITLE" --inputbox "$1" 12 76 "${2:-}"; }
passwordbox() { ui --stdout --title "$TITLE" --insecure --passwordbox "$1" 12 76 "${2:-}"; }
menu() { ui --stdout --title "$TITLE" --menu "$1" 22 82 13 "${@:2}"; }

need_docker() {
  if ! have docker || ! docker compose version >/dev/null 2>&1; then
    if ! install_docker_best_effort; then
      msgbox "Docker Engine with the Compose plugin is still unavailable. Install it, then rerun ./install.sh."
      return 1
    fi
  fi
  if ! docker info >/dev/null 2>&1; then
    msgbox "Docker is installed but this user cannot reach the daemon. Start Docker and/or add your user to the docker group, then rerun."
    return 1
  fi
}

dc() { docker compose --project-directory "$ROOT" -f "$ROOT/docker-compose.yml" "$@"; }

rand_hex() { openssl rand -hex "$1"; }
rand_secret() { openssl rand -base64 36 | tr -d '\n'; }

ensure_dirs() {
  mkdir -p "$CERT_DIR" "$SECRET_DIR" "$BACKUP_DIR" "$CONFIG_DIR"
  chmod 700 "$SECRET_DIR" "$CERT_DIR" 2>/dev/null || true
}

getenv_file() {
  local key="$1" fallback="${2:-}" value
  if [[ -f "$ENV_FILE" ]]; then
    value="$(grep -E "^${key}=" "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
    [[ -n "$value" ]] && { printf '%s' "$value"; return; }
  fi
  printf '%s' "$fallback"
}

write_env() {
  local signoz_endpoint="$1" signoz_key="$2" external_host="$3" admin_secure="$4" syslog_enabled="$5" collector="$6" lifetime="$7" ca_name="$8" ca_dns="$9"
  local session_key
  session_key="$(getenv_file SESSION_SIGNING_KEY)"
  [[ -z "$session_key" ]] && session_key="$(rand_hex 32)"

  cat > "$ENV_FILE" <<EOT
# Generated by scripts/install-tui.sh — rerun ./install.sh to reconfigure.
SIGNOZ_ENDPOINT=${signoz_endpoint}
SIGNOZ_INGESTION_KEY=${signoz_key}
SESSION_SIGNING_KEY=${session_key}
ADMIN_COOKIE_SECURE=${admin_secure}
TRUST_PROXY_HEADERS=false
MAX_BODY_BYTES=4194304
USAGE_RETENTION_DAYS=90

PROXY_BIND=0.0.0.0
PROXY_PORT=$(getenv_file PROXY_PORT 4318)
ADMIN_BIND=$(getenv_file ADMIN_BIND 127.0.0.1)
ADMIN_PORT=$(getenv_file ADMIN_PORT 8080)
SYSLOG_BIND=0.0.0.0
SYSLOG_PORT=$(getenv_file SYSLOG_PORT 6514)
CA_RENEWAL_BIND=0.0.0.0
CA_RENEWAL_PORT=$(getenv_file CA_RENEWAL_PORT 6543)

# Bundled Smallstep step-ca. Version pinned for reproducible installs.
STEP_CA_IMAGE=$(getenv_file STEP_CA_IMAGE smallstep/step-ca:0.30.2)
STEP_CA_BIND=$(getenv_file STEP_CA_BIND 127.0.0.1)
STEP_CA_PORT=$(getenv_file STEP_CA_PORT 9000)
STEP_CA_NAME=${ca_name}
STEP_CA_DNS_NAMES=${ca_dns}
CA_ENABLED=true
CA_PROVISIONER_NAME=otlp-proxy
CA_EXTERNAL_HOSTNAME=${external_host}
CA_CERT_LIFETIME=${lifetime}

SYSLOG_ENABLED=${syslog_enabled}
SYSLOG_COLLECTOR_ADDR=${collector}
OTELCOL_IMAGE=$(getenv_file OTELCOL_IMAGE otel/opentelemetry-collector-contrib:0.157.0)
SYSLOG_MAX_FRAME_BYTES=65536
SYSLOG_MAX_CONNECTIONS=1000
SYSLOG_MAX_CONNS_PER_TENANT=50
SYSLOG_CONN_IDLE_TIMEOUT=300s
EOT
  chmod 600 "$ENV_FILE"
  write_syslog_collector_config "$signoz_key"
}

write_syslog_collector_config() {
  local signoz_key="$1"
  mkdir -p "$CONFIG_DIR"

  cat > "$CONFIG_DIR/otelcol-syslog.yaml" <<'EOT'
# Generated by scripts/install-tui.sh.
# OTLP Proxy removes incoming octet-counting and forwards one stamped RFC5424
# message per newline over the private Compose network.
receivers:
  syslog:
    tcp:
      listen_address: 0.0.0.0:5140
      max_log_size: 1MiB
    protocol: rfc5424

processors:
  batch: {}

exporters:
  otlp_http/signoz:
    endpoint: ${env:SIGNOZ_ENDPOINT}
EOT

  if [[ -n "$signoz_key" ]]; then
    cat >> "$CONFIG_DIR/otelcol-syslog.yaml" <<'EOT'
    headers:
      Authorization: "Bearer ${env:SIGNOZ_INGESTION_KEY}"
EOT
  fi

  cat >> "$CONFIG_DIR/otelcol-syslog.yaml" <<'EOT'

service:
  pipelines:
    logs:
      receivers: [syslog]
      processors: [batch]
      exporters: [otlp_http/signoz]
EOT
  chmod 644 "$CONFIG_DIR/otelcol-syslog.yaml"
}

ensure_ca_password() {
  ensure_dirs
  if [[ ! -s "$SECRET_DIR/step-ca-password" ]]; then
    umask 077
    rand_secret > "$SECRET_DIR/step-ca-password"
    printf '\n' >> "$SECRET_DIR/step-ca-password"
  fi
  chmod 600 "$SECRET_DIR/step-ca-password"
}

wait_ca() {
  local i
  for i in $(seq 1 60); do
    if dc exec -T step-ca step ca health --ca-url https://127.0.0.1:9000 --root /home/step/certs/root_ca.crt >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  return 1
}

start_ca() {
  need_docker
  ensure_ca_password
  dc up -d step-ca
  if ! wait_ca; then
    dc logs --tail=120 step-ca > "$ROOT/step-ca-last.log" 2>&1 || true
    msgbox "step-ca did not become healthy. Last logs were written to step-ca-last.log."
    return 1
  fi
}

configure_ca_claims() {
  local lifetime prov
  lifetime="$(getenv_file CA_CERT_LIFETIME 2160h)"
  prov="$(getenv_file CA_PROVISIONER_NAME otlp-proxy)"
  # The default JWK provisioner max is typically 24h. Raise only this dedicated
  # provisioner's limits so the application's configured lifetime can be used.
  dc exec -T step-ca step ca provisioner update "$prov" \
    --x509-min-dur=5m \
    --x509-default-dur="$lifetime" \
    --x509-max-dur=8760h \
    --ca-config=/home/step/config/ca.json >/dev/null
  dc kill -s HUP step-ca >/dev/null 2>&1 || dc restart step-ca >/dev/null
  wait_ca
}

export_root() {
  ensure_dirs
  rm -f "$CERT_DIR/root.crt.tmp"
  dc cp step-ca:/home/step/certs/root_ca.crt "$CERT_DIR/root.crt.tmp" >/dev/null
  dc cp step-ca:/home/step/certs/intermediate_ca.crt "$CERT_DIR/intermediate.crt.tmp" >/dev/null
  mv "$CERT_DIR/root.crt.tmp" "$CERT_DIR/root.crt"
  mv "$CERT_DIR/intermediate.crt.tmp" "$CERT_DIR/intermediate.crt"
  # Clients generated by the application currently carry only their leaf PEM.
  # Trust both the issuing intermediate and root in the mTLS listener pool.
  cat "$CERT_DIR/intermediate.crt" "$CERT_DIR/root.crt" > "$CERT_DIR/client-ca.crt"
  chmod 644 "$CERT_DIR/root.crt" "$CERT_DIR/intermediate.crt" "$CERT_DIR/client-ca.crt"
}

export_provisioner_key() {
  ensure_dirs
  local encrypted
  encrypted="$(dc exec -T step-ca cat /home/step/config/ca.json | awk -F'"' '/"encryptedKey"/ {print $4; exit}' | tr -d '\r\n')"
  if [[ -z "$encrypted" ]]; then
    msgbox "Could not locate the initial JWK provisioner's encryptedKey in step-ca ca.json."
    return 1
  fi
  umask 077
  printf '%s' "$encrypted" | dc exec -T step-ca step crypto jwe decrypt --password-file /run/secrets/step_ca_password > "$CERT_DIR/provisioner.jwk"
  chmod 600 "$CERT_DIR/provisioner.jwk"
}

issue_listener_cert() {
  local host prov lifetime
  host="$(getenv_file CA_EXTERNAL_HOSTNAME)"
  prov="$(getenv_file CA_PROVISIONER_NAME otlp-proxy)"
  lifetime="$(getenv_file CA_CERT_LIFETIME 2160h)"
  [[ -n "$host" ]] || { msgbox "CA_EXTERNAL_HOSTNAME is empty."; return 1; }

  dc exec -T step-ca rm -f /tmp/otlp-proxy-server.crt /tmp/otlp-proxy-server.key
  dc exec -T step-ca step ca certificate "$host" \
    /tmp/otlp-proxy-server.crt /tmp/otlp-proxy-server.key \
    --ca-url=https://127.0.0.1:9000 \
    --root=/home/step/certs/root_ca.crt \
    --provisioner="$prov" \
    --provisioner-password-file=/run/secrets/step_ca_password \
    --not-after="$lifetime" \
    --san="$host" \
    --force >/dev/null

  dc cp step-ca:/tmp/otlp-proxy-server.crt "$CERT_DIR/server.crt" >/dev/null
  dc cp step-ca:/tmp/otlp-proxy-server.key "$CERT_DIR/server.key" >/dev/null
  # tls.LoadX509KeyPair sends every PEM certificate in server.crt. Ensure the
  # issuing intermediate is present so clients that trust only root.crt can
  # build the chain even if `step ca certificate` emitted only the leaf.
  if [[ $(grep -c 'BEGIN CERTIFICATE' "$CERT_DIR/server.crt" || true) -lt 2 && -f "$CERT_DIR/intermediate.crt" ]]; then
    cat "$CERT_DIR/intermediate.crt" >> "$CERT_DIR/server.crt"
  fi
  chmod 644 "$CERT_DIR/server.crt"
  chmod 600 "$CERT_DIR/server.key"
}

bootstrap_ca_material() {
  ui --infobox "Configuring bundled step-ca...\n\n• waiting for CA\n• configuring provisioner lifetime\n• exporting root\n• decrypting dedicated JWK key\n• issuing proxy listener certificate" 12 70
  configure_ca_claims
  export_root
  export_provisioner_key
  issue_listener_cert
}

wait_proxy() {
  local i
  for i in $(seq 1 45); do
    if dc exec -T proxy wget -q -O - http://127.0.0.1:4318/healthz >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  return 1
}

deploy_proxy() {
  need_docker
  [[ -f "$ENV_FILE" ]] || { msgbox "No .env yet. Run Quick install first."; return 1; }
  [[ -s "$CERT_DIR/provisioner.jwk" && -s "$CERT_DIR/root.crt" && -s "$CERT_DIR/server.crt" && -s "$CERT_DIR/server.key" ]] || {
    msgbox "Certificate material is incomplete. Run 'Repair / regenerate CA material' first."
    return 1
  }
  ui --infobox "Building and starting syslog collector + OTLP Proxy..." 8 60
  dc up -d syslog-collector
  dc up -d --build proxy
  if wait_proxy; then
    msgbox "Deployment is healthy.\n\nAdmin: http://$(getenv_file ADMIN_BIND 127.0.0.1):$(getenv_file ADMIN_PORT 8080)\nOTLP: $(getenv_file PROXY_BIND 0.0.0.0):$(getenv_file PROXY_PORT 4318)\nstep-ca: https://$(getenv_file STEP_CA_BIND 127.0.0.1):$(getenv_file STEP_CA_PORT 9000)\nRenewal mTLS: $(getenv_file CA_EXTERNAL_HOSTNAME):$(getenv_file CA_RENEWAL_PORT 6543)"
  else
    dc logs --tail=150 proxy > "$ROOT/proxy-last.log" 2>&1 || true
    msgbox "Proxy did not become healthy. Last logs were written to proxy-last.log."
    return 1
  fi
}

validate_certs_text() {
  local out="" host
  host="$(getenv_file CA_EXTERNAL_HOSTNAME)"
  if [[ -f "$CERT_DIR/root.crt" && -f "$CERT_DIR/server.crt" ]]; then
    out+="$(openssl verify -CAfile "$CERT_DIR/root.crt" "$CERT_DIR/server.crt" 2>&1)"$'\n'
    out+="$(openssl x509 -in "$CERT_DIR/server.crt" -noout -subject -issuer -dates -fingerprint -sha256 2>&1)"$'\n'
    [[ -n "$host" ]] && out+="$(openssl x509 -in "$CERT_DIR/server.crt" -noout -checkhost "$host" 2>&1 || true)"$'\n'
  else
    out+="Certificate material not generated yet."$'\n'
  fi
  if dc ps step-ca >/dev/null 2>&1; then
    out+=$'\nstep-ca health: '
    out+="$(dc exec -T step-ca step ca health --ca-url https://127.0.0.1:9000 --root /home/step/certs/root_ca.crt 2>&1 || true)"
  fi
  printf '%s' "$out"
}

show_validation() {
  local tmp
  tmp="$(mktemp)"; validate_certs_text > "$tmp"
  ui --title "Certificate / CA validation" --textbox "$tmp" 24 100
  rm -f "$tmp"
}

quick_install() {
  need_docker || return 1
  ensure_dirs
  local endpoint key host secure syslog collector lifetime ca_name ca_dns choice summary
  endpoint="$(inputbox "SigNoz OTLP HTTP endpoint reachable FROM the proxy container.\nExample: http://192.168.30.50:4318" "$(getenv_file SIGNOZ_ENDPOINT http://192.168.30.50:4318)")" || return 0
  key="$(passwordbox "SigNoz ingestion key (leave empty if your SigNoz does not require one)." "$(getenv_file SIGNOZ_INGESTION_KEY)")" || return 0
  host="$(inputbox "Public DNS name or IP clients use for this proxy's syslog/renewal TLS listener.\nThis becomes the server certificate SAN." "$(getenv_file CA_EXTERNAL_HOSTNAME "$(hostname -f 2>/dev/null || hostname)")")" || return 0
  ca_name="$(inputbox "Name for the bundled private certificate authority." "$(getenv_file STEP_CA_NAME "OTLP Proxy CA")")" || return 0
  ca_dns="$(inputbox "DNS/IP names for the step-ca SERVER itself (comma-separated). Keep 'step-ca' because the proxy uses Docker DNS." "$(getenv_file STEP_CA_DNS_NAMES "step-ca,localhost,127.0.0.1")")" || return 0
  choice="$(menu "Client certificate lifetime" 1 "24 hours (24h)" 2 "30 days (720h)" 3 "90 days (2160h, recommended)" 4 "180 days (4320h)")" || return 0
  case "$choice" in 1) lifetime=24h;; 2) lifetime=720h;; 4) lifetime=4320h;; *) lifetime=2160h;; esac
  if yesno "Will the Admin UI be accessed through HTTPS?\n\nChoose Yes behind an HTTPS reverse proxy. Choose No for direct http://127.0.0.1:8080 access."; then secure=true; else secure=false; fi
  if yesno "Enable syslog ingestion over mTLS on port $(getenv_file SYSLOG_PORT 6514)?"; then
    syslog=true
    collector="$(inputbox "Destination syslog collector address as seen FROM the proxy container.
For the bundled AIO collector, keep syslog-collector:5140." "$(getenv_file SYSLOG_COLLECTOR_ADDR syslog-collector:5140)")" || return 0
  else
    syslog=false; collector="$(getenv_file SYSLOG_COLLECTOR_ADDR syslog-collector:5140)"
  fi

  summary="SigNoz: $endpoint\nExternal TLS host: $host\nBundled CA: $ca_name\nProvisioner: otlp-proxy\nClient cert lifetime: $lifetime\nSyslog mTLS: $syslog\nAdmin Secure cookie: $secure\n\nThe installer will create a persistent step-ca volume, generate CA secrets, issue the proxy listener certificate, build the Go application, and start step-ca, the syslog collector, and the proxy."
  yesno "$summary\n\nContinue?" || return 0

  write_env "$endpoint" "$key" "$host" "$secure" "$syslog" "$collector" "$lifetime" "$ca_name" "$ca_dns"
  ensure_ca_password
  start_ca
  bootstrap_ca_material
  deploy_proxy
}

repair_ca() {
  need_docker || return 1
  [[ -f "$ENV_FILE" ]] || { msgbox "Run Quick install first."; return 1; }
  start_ca
  bootstrap_ca_material
  msgbox "CA material regenerated successfully. Restart the proxy if it is already running."
}

rotate_listener_cert() {
  need_docker || return 1
  start_ca
  configure_ca_claims
  export_root
  issue_listener_cert
  if dc ps --status running proxy 2>/dev/null | grep -q proxy; then dc restart proxy >/dev/null; fi
  msgbox "Listener certificate rotated and proxy restarted."
}

show_fingerprint() {
  if [[ ! -f "$CERT_DIR/root.crt" ]]; then msgbox "No root.crt yet."; return; fi
  local fp
  fp="$(openssl x509 -in "$CERT_DIR/root.crt" -outform der | openssl dgst -sha256 -hex | awk '{print $2}')"
  msgbox "step-ca root SHA-256 fingerprint:\n\n$fp"
}

show_password() {
  [[ -f "$SECRET_DIR/step-ca-password" ]] || { msgbox "No bundled CA password exists yet."; return; }
  yesno "The CA password decrypts the online intermediate key and default JWK provisioner. Display it on screen?" || return
  msgbox "Bundled step-ca password:\n\n$(cat "$SECRET_DIR/step-ca-password")\n\nProtect backups of this value."
}

backup_all() {
  need_docker || return 1
  local stamp dest
  stamp="$(date +%Y%m%d-%H%M%S)"; dest="$BACKUP_DIR/$stamp"; mkdir -p "$dest"
  cp -a "$ENV_FILE" "$dest/.env" 2>/dev/null || true
  cp -a "$CERT_DIR" "$SECRET_DIR" "$dest/" 2>/dev/null || true
  if dc ps --status running step-ca 2>/dev/null | grep -q step-ca; then
    dc exec -T step-ca tar czf - -C /home/step . > "$dest/step-ca-data.tar.gz"
  fi
  if dc ps --status running proxy 2>/dev/null | grep -q proxy; then
    dc exec -T proxy tar czf - -C /data . > "$dest/proxy-data.tar.gz"
  fi
  chmod -R go-rwx "$dest" 2>/dev/null || true
  msgbox "Backup created:\n\n$dest\n\nIt contains sensitive CA and application material."
}

show_status() {
  need_docker || return 1
  local tmp="$(mktemp)"
  { echo "== Containers =="; dc ps; echo; echo "== Certificates =="; validate_certs_text; } > "$tmp" 2>&1
  ui --title "OTLP Proxy status" --textbox "$tmp" 28 110
  rm -f "$tmp"
}

logs_service() {
  need_docker || return 1
  local service="$1"
  clear
  echo "Following $service logs. Press Ctrl-C to return to the TUI."
  dc logs --tail=100 -f "$service" || true
}

ca_tools() {
  while true; do
    local c
    c="$(menu "Certificate Authority / certificate tools" \
      1 "Repair / regenerate exported CA material" \
      2 "Rotate proxy TLS listener certificate" \
      3 "Validate CA and listener certificates" \
      4 "Show root CA fingerprint" \
      5 "Show bundled CA password" \
      6 "Export root CA path" \
      0 "Back")" || return
    case "$c" in
      1) repair_ca;;
      2) rotate_listener_cert;;
      3) show_validation;;
      4) show_fingerprint;;
      5) show_password;;
      6) msgbox "Root CA for client trust distribution:\n\n$CERT_DIR/root.crt";;
      0) return;;
    esac
  done
}

stop_stack() { need_docker || return 1; dc stop; msgbox "OTLP Proxy, syslog collector, and bundled step-ca stopped. Persistent volumes were kept."; }
start_stack() { need_docker || return 1; dc up -d; msgbox "Stack start requested. Use Status to verify health."; }

main_menu() {
  while true; do
    local c
    c="$(menu "All-in-one installer and operations console\nBundled step-ca is initialized automatically and CA_ENABLED is always true." \
      1 "Quick install / reconfigure everything" \
      2 "Deploy / rebuild proxy" \
      3 "Certificate / step-ca tools" \
      4 "Status & certificate validation" \
      5 "Start stack" \
      6 "Stop stack (keep data)" \
      7 "Follow proxy logs" \
      8 "Follow step-ca logs" \
      9 "Follow syslog collector logs" \
      10 "Backup app + CA" \
      0 "Exit")" || break
    case "$c" in
      1) quick_install;;
      2) deploy_proxy;;
      3) ca_tools;;
      4) show_status;;
      5) start_stack;;
      6) stop_stack;;
      7) logs_service proxy;;
      8) logs_service step-ca;;
      9) logs_service syslog-collector;;
      10) backup_all;;
      0) break;;
    esac
  done
  clear
}

main_menu
